### ISSUE TITLE
Travis URL

### ISSUE THREAD

**Issue by amarjandu** [csc340-03-fall-2016/WIKI#1]
There seems to be an error within the wiki, the url for the build service TRAVIS is, https://travis-ci.org not www.travis.org .

**Comment by Omarasifshaikh** [comment]
Thanks for the report @amarjandu , can you please point out to where this error is? Thanks.

**Comment by amarjandu** [comment]
https://github.com/csc340-03-fall-2016/WIKI/wiki/Getting-started-for-CSC-340

Section Travis, bullet point 5
 
Error: 
log into travis.org and enable the repository( allow the pushes to be built)
Correction
log into travis-ci.org and enable the repository( allow the pushes to be built)

**Comment by Omarasifshaikh** [comment]
Fixed. Thank you!
